#!/bin/sh

./configure \
 -prefix $HOME/Qt/5.4-android/5.4/android-armv5 \
 -opensource \
 -confirm-license \
 -developer-build \
 -release \
 -make libs \
 -make tools \
 -xplatform android-g++ \
 -nomake tests \
 -nomake examples \
 -android-ndk-host linux-x86_64 \
 -android-ndk $HOME/android/android-ndk-r10c \
 -android-sdk $HOME/android/android-sdk-linux \
 -android-toolchain-version 4.9 \
 -android-ndk-platform android-10 \
 -android-arch armeabi \
 -skip qttranslations \
 -skip qtwebkit \
 -skip qtserialport \
 -skip qtwebkit-examples
