#!/bin/sh

S=$HOME/Qt/5.1.1/5.1.1/android-armv5
D=$HOME/dev/apps/ide/jqt/android/libs/armeabi
E=$HOME/dev/apps/ide/jqt/android/assets/--Managed_by_Qt_Creator--

mkdir -p ${D}
mkdir -p ${E}

cp -r ${S}/imports ${E}/.
cp -r ${S}/plugins ${E}/.
cp -r ${S}/qml ${E}/.
find ${E} -name '*.so' -delete

cp ${ANDROID_NDK_ROOT}/prebuilt/android-arm/gdbserver/gdbserver ${D}/.
cp ${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/${ANDROID_NDK_TOOLCHAIN_VERSION}/libs/${ANDROID_TARGET_ARCH}/thumb/libgnustl_shared.so ${D}/.

cp ${S}/jar/QtAndroid-bundled.jar ${D}/../--Managed_by_Qt_Creator--QtAndroid-bundled.jar
cp ${S}/jar/QtMultimedia-bundled.jar ${D}/../--Managed_by_Qt_Creator--QtMultimedia-bundled.jar
cp ${S}/jar/QtSensors-bundled.jar ${D}/../--Managed_by_Qt_Creator--QtSensors-bundled.jar

cp ${S}/imports/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.so ${D}/lib--Managed_by_Qt_Creator--imports_Qt_labs_folderlistmodel_libqmlfolderlistmodelplugin.so
cp ${S}/imports/Qt/labs/gestures/libqmlgesturesplugin.so ${D}/lib--Managed_by_Qt_Creator--imports_Qt_labs_gestures_libqmlgesturesplugin.so
cp ${S}/imports/Qt/labs/particles/libqmlparticlesplugin.so ${D}/lib--Managed_by_Qt_Creator--imports_Qt_labs_particles_libqmlparticlesplugin.so
cp ${S}/imports/Qt/labs/shaders/libqmlshadersplugin.so ${D}/lib--Managed_by_Qt_Creator--imports_Qt_labs_shaders_libqmlshadersplugin.so
cp ${S}/plugins/accessible/libqtaccessiblequick.so ${D}/lib--Managed_by_Qt_Creator--plugins_accessible_libqtaccessiblequick.so
cp ${S}/plugins/accessible/libqtaccessiblewidgets.so ${D}/lib--Managed_by_Qt_Creator--plugins_accessible_libqtaccessiblewidgets.so
cp ${S}/plugins/bearer/libqgenericbearer.so ${D}/lib--Managed_by_Qt_Creator--plugins_bearer_libqgenericbearer.so
cp ${S}/plugins/imageformats/libqgif.so ${D}/lib--Managed_by_Qt_Creator--plugins_imageformats_libqgif.so
cp ${S}/plugins/imageformats/libqico.so ${D}/lib--Managed_by_Qt_Creator--plugins_imageformats_libqico.so
cp ${S}/plugins/imageformats/libqjpeg.so ${D}/lib--Managed_by_Qt_Creator--plugins_imageformats_libqjpeg.so
cp ${S}/plugins/imageformats/libqmng.so ${D}/lib--Managed_by_Qt_Creator--plugins_imageformats_libqmng.so
cp ${S}/plugins/imageformats/libqsvg.so ${D}/lib--Managed_by_Qt_Creator--plugins_imageformats_libqsvg.so
cp ${S}/plugins/imageformats/libqtga.so ${D}/lib--Managed_by_Qt_Creator--plugins_imageformats_libqtga.so
cp ${S}/plugins/imageformats/libqtiff.so ${D}/lib--Managed_by_Qt_Creator--plugins_imageformats_libqtiff.so
cp ${S}/plugins/imageformats/libqwbmp.so ${D}/lib--Managed_by_Qt_Creator--plugins_imageformats_libqwbmp.so
cp ${S}/plugins/mediaservice/libandroidmediaplayer.so ${D}/lib--Managed_by_Qt_Creator--plugins_mediaservice_libandroidmediaplayer.so
cp ${S}/plugins/mediaservice/libqtmedia_audioengine.so ${D}/lib--Managed_by_Qt_Creator--plugins_mediaservice_libqtmedia_audioengine.so
cp ${S}/plugins/platforms/android/libqtforandroidGL.so ${D}/lib--Managed_by_Qt_Creator--plugins_platforms_android_libqtforandroidGL.so
cp ${S}/plugins/platforms/android/libqtforandroid.so ${D}/lib--Managed_by_Qt_Creator--plugins_platforms_android_libqtforandroid.so
cp ${S}/plugins/platforms/libqeglfs.so ${D}/lib--Managed_by_Qt_Creator--plugins_platforms_libqeglfs.so
cp ${S}/plugins/platforms/libqminimalegl.so ${D}/lib--Managed_by_Qt_Creator--plugins_platforms_libqminimalegl.so
cp ${S}/plugins/platforms/libqminimal.so ${D}/lib--Managed_by_Qt_Creator--plugins_platforms_libqminimal.so
cp ${S}/plugins/platforms/libqoffscreen.so ${D}/lib--Managed_by_Qt_Creator--plugins_platforms_libqoffscreen.so
cp ${S}/plugins/sensorgestures/libqtsensorgestures_plugin.so ${D}/lib--Managed_by_Qt_Creator--plugins_sensorgestures_libqtsensorgestures_plugin.so
cp ${S}/plugins/sensorgestures/libqtsensorgestures_shakeplugin.so ${D}/lib--Managed_by_Qt_Creator--plugins_sensorgestures_libqtsensorgestures_shakeplugin.so
cp ${S}/plugins/sensors/libqtsensors_android.so ${D}/lib--Managed_by_Qt_Creator--plugins_sensors_libqtsensors_android.so
cp ${S}/plugins/sensors/libqtsensors_generic.so ${D}/lib--Managed_by_Qt_Creator--plugins_sensors_libqtsensors_generic.so
cp ${S}/plugins/sqldrivers/libqsqlite.so ${D}/lib--Managed_by_Qt_Creator--plugins_sqldrivers_libqsqlite.so
cp ${S}/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_Qt_labs_folderlistmodel_libqmlfolderlistmodelplugin.so
cp ${S}/qml/QtMultimedia/libdeclarative_multimedia.so ${D}/lib--Managed_by_Qt_Creator--qml_QtMultimedia_libdeclarative_multimedia.so
cp ${S}/qml/QtQml/Models.2/libmodelsplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQml_Models.2_libmodelsplugin.so
cp ${S}/qml/QtQuick.2/libqtquick2plugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick.2_libqtquick2plugin.so
cp ${S}/qml/QtQuick/Controls/libqtquickcontrolsplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick_Controls_libqtquickcontrolsplugin.so
cp ${S}/qml/QtQuick/Controls/Private/libqtquickcontrolsprivateplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick_Controls_Private_libqtquickcontrolsprivateplugin.so
cp ${S}/qml/QtQuick/Dialogs/libdialogplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick_Dialogs_libdialogplugin.so
cp ${S}/qml/QtQuick/Layouts/libqquicklayoutsplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick_Layouts_libqquicklayoutsplugin.so
cp ${S}/qml/QtQuick/LocalStorage/libqmllocalstorageplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick_LocalStorage_libqmllocalstorageplugin.so
cp ${S}/qml/QtQuick/Particles.2/libparticlesplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick_Particles.2_libparticlesplugin.so
cp ${S}/qml/QtQuick/PrivateWidgets/libwidgetsplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick_PrivateWidgets_libwidgetsplugin.so
cp ${S}/qml/QtQuick/Window.2/libwindowplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick_Window.2_libwindowplugin.so
cp ${S}/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtQuick_XmlListModel_libqmlxmllistmodelplugin.so
cp ${S}/qml/QtSensors/libdeclarative_sensors.so ${D}/lib--Managed_by_Qt_Creator--qml_QtSensors_libdeclarative_sensors.so
cp ${S}/qml/QtTest/libqmltestplugin.so ${D}/lib--Managed_by_Qt_Creator--qml_QtTest_libqmltestplugin.so
cp ${S}/lib/libQt5CLucene.so ${D}/libQt5CLucene.so
cp ${S}/lib/libQt5Concurrent.so ${D}/libQt5Concurrent.so
cp ${S}/lib/libQt5Core.so ${D}/libQt5Core.so
cp ${S}/lib/libQt5Declarative.so ${D}/libQt5Declarative.so
cp ${S}/lib/libQt5Gui.so ${D}/libQt5Gui.so
cp ${S}/lib/libQt5Help.so ${D}/libQt5Help.so
cp ${S}/lib/libQt5MultimediaQuick_p.so ${D}/libQt5MultimediaQuick_p.so
cp ${S}/lib/libQt5Multimedia.so ${D}/libQt5Multimedia.so
cp ${S}/lib/libQt5MultimediaWidgets.so ${D}/libQt5MultimediaWidgets.so
cp ${S}/lib/libQt5Network.so ${D}/libQt5Network.so
cp ${S}/lib/libQt5OpenGL.so ${D}/libQt5OpenGL.so
cp ${S}/lib/libQt5PrintSupport.so ${D}/libQt5PrintSupport.so
cp ${S}/lib/libQt5Qml.so ${D}/libQt5Qml.so
cp ${S}/lib/libQt5QuickParticles.so ${D}/libQt5QuickParticles.so
cp ${S}/lib/libQt5Quick.so ${D}/libQt5Quick.so
cp ${S}/lib/libQt5QuickTest.so ${D}/libQt5QuickTest.so
cp ${S}/lib/libQt5Script.so ${D}/libQt5Script.so
cp ${S}/lib/libQt5ScriptTools.so ${D}/libQt5ScriptTools.so
cp ${S}/lib/libQt5Sensors.so ${D}/libQt5Sensors.so
cp ${S}/lib/libQt5Sql.so ${D}/libQt5Sql.so
cp ${S}/lib/libQt5Svg.so ${D}/libQt5Svg.so
cp ${S}/lib/libQt5Test.so ${D}/libQt5Test.so
cp ${S}/lib/libQt5V8.so ${D}/libQt5V8.so
cp ${S}/lib/libQt5Widgets.so ${D}/libQt5Widgets.so
cp ${S}/lib/libQt5XmlPatterns.so ${D}/libQt5XmlPatterns.so
cp ${S}/lib/libQt5Xml.so ${D}/libQt5Xml.so
