#ifndef QTJNI_H
#define QTJNI_H

#include <jni.h>

extern "C" {
  Dllexport void javaOnLoad (void *,jclass,jclass);
  Dllexport int GetJavaVMENV(JavaVM ** pvm, JNIEnv ** penv);
  Dllexport jclass GetClassID(int id);

  Dllexport jint GetVersion();
  Dllexport jclass DefineClass(const char *name, jobject loader, const jbyte *buf, jsize len);
  Dllexport jclass FindClass(const char *name);
  Dllexport jmethodID FromReflectedMethod(jobject method);
  Dllexport jfieldID FromReflectedField(jobject field);
  Dllexport jobject ToReflectedMethod(jclass cls, jmethodID methodID, jboolean isStatic);
  Dllexport jclass GetSuperclass(jclass sub);
  Dllexport jboolean IsAssignableFrom(jclass sub, jclass sup);
  Dllexport jobject ToReflectedField(jclass cls, jfieldID fieldID, jboolean isStatic);
  Dllexport jint Throw(jthrowable obj);
  Dllexport jint ThrowNew(jclass clazz, const char *msg);
  Dllexport jthrowable ExceptionOccurred();
  Dllexport void ExceptionDescribe();
  Dllexport void ExceptionClear();
  Dllexport void FatalError(const char *msg);
  Dllexport jint PushLocalFrame(jint capacity);
  Dllexport jobject PopLocalFrame(jobject result);
  Dllexport jobject NewGlobalRef(jobject lobj);
  Dllexport void DeleteGlobalRef(jobject gref);
  Dllexport void DeleteLocalRef(jobject obj);
  Dllexport jboolean IsSameObject(jobject obj1, jobject obj2);
  Dllexport jobject NewLocalRef(jobject ref);
  Dllexport jint EnsureLocalCapacity(jint capacity);
  Dllexport jobject AllocObject(jclass clazz);
  Dllexport jobject NewObject(jclass clazz, jmethodID methodID, ...);
  Dllexport jobject NewObjectV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jobject NewObjectA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport jclass GetObjectClass(jobject obj);
  Dllexport jboolean IsInstanceOf(jobject obj, jclass clazz);
  Dllexport jmethodID GetMethodID(jclass clazz, const char *name, const char *sig);
  Dllexport jobject CallObjectMethod(jobject obj, jmethodID methodID, ...);
  Dllexport jobject CallObjectMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport jobject CallObjectMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport jboolean CallBooleanMethod(jobject obj, jmethodID methodID, ...);
  Dllexport jboolean CallBooleanMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport jboolean CallBooleanMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport jbyte CallByteMethod(jobject obj, jmethodID methodID, ...);
  Dllexport jbyte CallByteMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport jbyte CallByteMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport jchar CallCharMethod(jobject obj, jmethodID methodID, ...);
  Dllexport jchar CallCharMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport jchar CallCharMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport jshort CallShortMethod(jobject obj, jmethodID methodID, ...);
  Dllexport jshort CallShortMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport jshort CallShortMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport jint CallIntMethod(jobject obj, jmethodID methodID, ...);
  Dllexport jint CallIntMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport jint CallIntMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport jlong CallLongMethod(jobject obj, jmethodID methodID, ...);
  Dllexport jlong CallLongMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport jlong CallLongMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport jfloat CallFloatMethod(jobject obj, jmethodID methodID, ...);
  Dllexport jfloat CallFloatMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport jfloat CallFloatMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport jdouble CallDoubleMethod(jobject obj, jmethodID methodID, ...);
  Dllexport jdouble CallDoubleMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport jdouble CallDoubleMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport void CallVoidMethod(jobject obj, jmethodID methodID, ...);
  Dllexport void CallVoidMethodV(jobject obj, jmethodID methodID, va_list args);
  Dllexport void CallVoidMethodA(jobject obj, jmethodID methodID, const jvalue * args);
  Dllexport jobject CallNonvirtualObjectMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport jobject CallNonvirtualObjectMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport jobject CallNonvirtualObjectMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport jboolean CallNonvirtualBooleanMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport jboolean CallNonvirtualBooleanMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport jboolean CallNonvirtualBooleanMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport jbyte CallNonvirtualByteMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport jbyte CallNonvirtualByteMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport jbyte CallNonvirtualByteMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport jchar CallNonvirtualCharMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport jchar CallNonvirtualCharMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport jchar CallNonvirtualCharMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport jshort CallNonvirtualShortMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport jshort CallNonvirtualShortMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport jshort CallNonvirtualShortMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport jint CallNonvirtualIntMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport jint CallNonvirtualIntMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport jint CallNonvirtualIntMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport jlong CallNonvirtualLongMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport jlong CallNonvirtualLongMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport jlong CallNonvirtualLongMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport jfloat CallNonvirtualFloatMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport jfloat CallNonvirtualFloatMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport jfloat CallNonvirtualFloatMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport jdouble CallNonvirtualDoubleMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport jdouble CallNonvirtualDoubleMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport jdouble CallNonvirtualDoubleMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport void CallNonvirtualVoidMethod(jobject obj, jclass clazz, jmethodID methodID, ...);
  Dllexport void CallNonvirtualVoidMethodV(jobject obj, jclass clazz, jmethodID methodID, va_list args);
  Dllexport void CallNonvirtualVoidMethodA(jobject obj, jclass clazz, jmethodID methodID, const jvalue * args);
  Dllexport jfieldID GetFieldID(jclass clazz, const char *name, const char *sig);
  Dllexport jobject GetObjectField(jobject obj, jfieldID fieldID);
  Dllexport jboolean GetBooleanField(jobject obj, jfieldID fieldID);
  Dllexport jbyte GetByteField(jobject obj, jfieldID fieldID);
  Dllexport jchar GetCharField(jobject obj, jfieldID fieldID);
  Dllexport jshort GetShortField(jobject obj, jfieldID fieldID);
  Dllexport jint GetIntField(jobject obj, jfieldID fieldID);
  Dllexport jlong GetLongField(jobject obj, jfieldID fieldID);
  Dllexport jfloat GetFloatField(jobject obj, jfieldID fieldID);
  Dllexport jdouble GetDoubleField(jobject obj, jfieldID fieldID);
  Dllexport void SetObjectField(jobject obj, jfieldID fieldID, jobject val);
  Dllexport void SetBooleanField(jobject obj, jfieldID fieldID, jboolean val);
  Dllexport void SetByteField(jobject obj, jfieldID fieldID, jbyte val);
  Dllexport void SetCharField(jobject obj, jfieldID fieldID, jchar val);
  Dllexport void SetShortField(jobject obj, jfieldID fieldID, jshort val);
  Dllexport void SetIntField(jobject obj, jfieldID fieldID, jint val);
  Dllexport void SetLongField(jobject obj, jfieldID fieldID, jlong val);
  Dllexport void SetFloatField(jobject obj, jfieldID fieldID, jfloat val);
  Dllexport void SetDoubleField(jobject obj, jfieldID fieldID, jdouble val);
  Dllexport jmethodID GetStaticMethodID(jclass clazz, const char *name, const char *sig);
  Dllexport jobject CallStaticObjectMethod(jclass clazz, jmethodID methodID, ...);
  Dllexport jobject CallStaticObjectMethodV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jobject CallStaticObjectMethodA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport jboolean CallStaticBooleanMethod(jclass clazz, jmethodID methodID, ...);
  Dllexport jboolean CallStaticBooleanMethodV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jboolean CallStaticBooleanMethodA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport jbyte CallStaticByteMethod(jclass clazz, jmethodID methodID, ...);
  Dllexport jbyte CallStaticByteMethodV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jbyte CallStaticByteMethodA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport jchar CallStaticCharMethod(jclass clazz, jmethodID methodID, ...);
  Dllexport jchar CallStaticCharMethodV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jchar CallStaticCharMethodA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport jshort CallStaticShortMethod(jclass clazz, jmethodID methodID, ...);
  Dllexport jshort CallStaticShortMethodV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jshort CallStaticShortMethodA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport jint CallStaticIntMethod(jclass clazz, jmethodID methodID, ...);
  Dllexport jint CallStaticIntMethodV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jint CallStaticIntMethodA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport jlong CallStaticLongMethod(jclass clazz, jmethodID methodID, ...);
  Dllexport jlong CallStaticLongMethodV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jlong CallStaticLongMethodA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport jfloat CallStaticFloatMethod(jclass clazz, jmethodID methodID, ...);
  Dllexport jfloat CallStaticFloatMethodV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jfloat CallStaticFloatMethodA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport jdouble CallStaticDoubleMethod(jclass clazz, jmethodID methodID, ...);
  Dllexport jdouble CallStaticDoubleMethodV(jclass clazz, jmethodID methodID, va_list args);
  Dllexport jdouble CallStaticDoubleMethodA(jclass clazz, jmethodID methodID, const jvalue *args);
  Dllexport void CallStaticVoidMethod(jclass cls, jmethodID methodID, ...);
  Dllexport void CallStaticVoidMethodV(jclass cls, jmethodID methodID, va_list args);
  Dllexport void CallStaticVoidMethodA(jclass cls, jmethodID methodID, const jvalue * args);
  Dllexport jfieldID GetStaticFieldID(jclass clazz, const char *name, const char *sig);
  Dllexport jobject GetStaticObjectField(jclass clazz, jfieldID fieldID);
  Dllexport jboolean GetStaticBooleanField(jclass clazz, jfieldID fieldID);
  Dllexport jbyte GetStaticByteField(jclass clazz, jfieldID fieldID);
  Dllexport jchar GetStaticCharField(jclass clazz, jfieldID fieldID);
  Dllexport jshort GetStaticShortField(jclass clazz, jfieldID fieldID);
  Dllexport jint GetStaticIntField(jclass clazz, jfieldID fieldID);
  Dllexport jlong GetStaticLongField(jclass clazz, jfieldID fieldID);
  Dllexport jfloat GetStaticFloatField(jclass clazz, jfieldID fieldID);
  Dllexport jdouble GetStaticDoubleField(jclass clazz, jfieldID fieldID);
  Dllexport void SetStaticObjectField(jclass clazz, jfieldID fieldID, jobject value);
  Dllexport void SetStaticBooleanField(jclass clazz, jfieldID fieldID, jboolean value);
  Dllexport void SetStaticByteField(jclass clazz, jfieldID fieldID, jbyte value);
  Dllexport void SetStaticCharField(jclass clazz, jfieldID fieldID, jchar value);
  Dllexport void SetStaticShortField(jclass clazz, jfieldID fieldID, jshort value);
  Dllexport void SetStaticIntField(jclass clazz, jfieldID fieldID, jint value);
  Dllexport void SetStaticLongField(jclass clazz, jfieldID fieldID, jlong value);
  Dllexport void SetStaticFloatField(jclass clazz, jfieldID fieldID, jfloat value);
  Dllexport void SetStaticDoubleField(jclass clazz, jfieldID fieldID, jdouble value);
  Dllexport jstring NewString(const jchar *unicode, jsize len);
  Dllexport jsize GetStringLength(jstring str);
  Dllexport const jchar *GetStringChars(jstring str, jboolean *isCopy);
  Dllexport void ReleaseStringChars(jstring str, const jchar *chars);
  Dllexport jstring NewStringUTF(const char *utf);
  Dllexport jsize GetStringUTFLength(jstring str);
  Dllexport const char* GetStringUTFChars(jstring str, jboolean *isCopy);
  Dllexport void ReleaseStringUTFChars(jstring str, const char* chars);
  Dllexport jsize GetArrayLength(jarray array);
  Dllexport jobjectArray NewObjectArray(jsize len, jclass clazz, jobject init);
  Dllexport jobject GetObjectArrayElement(jobjectArray array, jsize index);
  Dllexport void SetObjectArrayElement(jobjectArray array, jsize index, jobject val);
  Dllexport jbooleanArray NewBooleanArray(jsize len);
  Dllexport jbyteArray NewByteArray(jsize len);
  Dllexport jcharArray NewCharArray(jsize len);
  Dllexport jshortArray NewShortArray(jsize len);
  Dllexport jintArray NewIntArray(jsize len);
  Dllexport jlongArray NewLongArray(jsize len);
  Dllexport jfloatArray NewFloatArray(jsize len);
  Dllexport jdoubleArray NewDoubleArray(jsize len);
  Dllexport jboolean * GetBooleanArrayElements(jbooleanArray array, jboolean *isCopy);
  Dllexport jbyte * GetByteArrayElements(jbyteArray array, jboolean *isCopy);
  Dllexport jchar * GetCharArrayElements(jcharArray array, jboolean *isCopy);
  Dllexport jshort * GetShortArrayElements(jshortArray array, jboolean *isCopy);
  Dllexport jint * GetIntArrayElements(jintArray array, jboolean *isCopy);
  Dllexport jlong * GetLongArrayElements(jlongArray array, jboolean *isCopy);
  Dllexport jfloat * GetFloatArrayElements(jfloatArray array, jboolean *isCopy);
  Dllexport jdouble * GetDoubleArrayElements(jdoubleArray array, jboolean *isCopy);
  Dllexport void ReleaseBooleanArrayElements(jbooleanArray array, jboolean *elems, jint mode);
  Dllexport void ReleaseByteArrayElements(jbyteArray array, jbyte *elems, jint mode);
  Dllexport void ReleaseCharArrayElements(jcharArray array, jchar *elems, jint mode);
  Dllexport void ReleaseShortArrayElements(jshortArray array, jshort *elems, jint mode);
  Dllexport void ReleaseIntArrayElements(jintArray array, jint *elems, jint mode);
  Dllexport void ReleaseLongArrayElements(jlongArray array, jlong *elems, jint mode);
  Dllexport void ReleaseFloatArrayElements(jfloatArray array, jfloat *elems, jint mode);
  Dllexport void ReleaseDoubleArrayElements(jdoubleArray array, jdouble *elems, jint mode);
  Dllexport void GetBooleanArrayRegion(jbooleanArray array, jsize start, jsize len, jboolean *buf);
  Dllexport void GetByteArrayRegion(jbyteArray array, jsize start, jsize len, jbyte *buf);
  Dllexport void GetCharArrayRegion(jcharArray array, jsize start, jsize len, jchar *buf);
  Dllexport void GetShortArrayRegion(jshortArray array, jsize start, jsize len, jshort *buf);
  Dllexport void GetIntArrayRegion(jintArray array, jsize start, jsize len, jint *buf);
  Dllexport void GetLongArrayRegion(jlongArray array, jsize start, jsize len, jlong *buf);
  Dllexport void GetFloatArrayRegion(jfloatArray array, jsize start, jsize len, jfloat *buf);
  Dllexport void GetDoubleArrayRegion(jdoubleArray array, jsize start, jsize len, jdouble *buf);
  Dllexport void SetBooleanArrayRegion(jbooleanArray array, jsize start, jsize len, const jboolean *buf);
  Dllexport void SetByteArrayRegion(jbyteArray array, jsize start, jsize len, const jbyte *buf);
  Dllexport void SetCharArrayRegion(jcharArray array, jsize start, jsize len, const jchar *buf);
  Dllexport void SetShortArrayRegion(jshortArray array, jsize start, jsize len, const jshort *buf);
  Dllexport void SetIntArrayRegion(jintArray array, jsize start, jsize len, const jint *buf);
  Dllexport void SetLongArrayRegion(jlongArray array, jsize start, jsize len, const jlong *buf);
  Dllexport void SetFloatArrayRegion(jfloatArray array, jsize start, jsize len, const jfloat *buf);
  Dllexport void SetDoubleArrayRegion(jdoubleArray array, jsize start, jsize len, const jdouble *buf);
  Dllexport jint RegisterNatives(jclass clazz, const JNINativeMethod *methods, jint nMethods);
  Dllexport jint UnregisterNatives(jclass clazz);
  Dllexport jint MonitorEnter(jobject obj);
  Dllexport jint MonitorExit(jobject obj);
  Dllexport jint GetJavaVM(JavaVM **vm);
  Dllexport void GetStringRegion(jstring str, jsize start, jsize len, jchar *buf);
  Dllexport void GetStringUTFRegion(jstring str, jsize start, jsize len, char *buf);
  Dllexport void * GetPrimitiveArrayCritical(jarray array, jboolean *isCopy);
  Dllexport void ReleasePrimitiveArrayCritical(jarray array, void *carray, jint mode);
  Dllexport const jchar * GetStringCritical(jstring string, jboolean *isCopy);
  Dllexport void ReleaseStringCritical(jstring string, const jchar *cstring);
  Dllexport jweak NewWeakGlobalRef(jobject obj);
  Dllexport void DeleteWeakGlobalRef(jweak ref);
  Dllexport jboolean ExceptionCheck();
  Dllexport jobject NewDirectByteBuffer(void* address, jlong capacity);
  Dllexport void* GetDirectBufferAddress(jobject buf);
  Dllexport jlong GetDirectBufferCapacity(jobject buf);
  Dllexport jobjectRefType GetObjectRefType(jobject obj);

}

#endif
