name: JQtide

on:
 push:
  branches:
   - excel

jobs:

# windows --------------------------------------------------------------
 jqtwin:
  name: JQtide (Windows)
  runs-on: windows-2019
  steps:
   - name: Check Git repository
     uses: actions/checkout@v4
     with:
      submodules: recursive

   - name: Setup Environment (Windows)
     uses: ilammy/msvc-dev-cmd@v1
     with:
      arch: amd64

   - name: Install Qt from source
     uses: jurplel/install-qt-action@v4
     with:
      version: '6.8.2'
      target: 'desktop'
      arch: 'win64_msvc2022_64'
      dir: '${{github.workspace}}'
#      modules: 'qtwebengine qt5compat qtwebsockets qtmultimedia qtwebchannel qtpositioning'
      modules: 'all'
      aqtversion: '==3.1.*'

   - name: Compile JQtide
     shell: cmd
     run: script\makewin.cmd 6.8.2 x64

   - name: Release JQtide
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: "jqt-win.zip,jqt-win-slim.zip"
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true
